// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCrowdRelation = "crowd_relation"

// CrowdRelation mapped from table <crowd_relation>
type CrowdRelation struct {
	CrowdRelationID int64 `gorm:"column:crowd_relation_id;type:bigint;primaryKey;autoIncrement:true" json:"crowd_relation_id"` // 人群关系ID
	UserID          int64 `gorm:"column:user_id;type:bigint;not null" json:"user_id"`                                          // 用户ID
	CrowdID         int64 `gorm:"column:crowd_id;type:bigint;not null" json:"crowd_id"`                                        // 人群ID
}

// TableName CrowdRelation's table name
func (*CrowdRelation) TableName() string {
	return TableNameCrowdRelation
}
