// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCrowdRule = "crowd_rule"

// CrowdRule mapped from table <crowd_rule>
type CrowdRule struct {
	CrowdRuleID  int64  `gorm:"column:crowd_rule_id;type:bigint;primaryKey;autoIncrement:true" json:"crowd_rule_id"` // 人群规则ID
	LabelID      int64  `gorm:"column:label_id;type:bigint;not null" json:"label_id"`                                // 关联的标签ID
	LabelData    string `gorm:"column:label_data;type:text;not null" json:"label_data"`                              // 关联的标签值
	DivideAction int64  `gorm:"column:divide_action;type:int;not null" json:"divide_action"`                         // 划分操作
}

// TableName CrowdRule's table name
func (*CrowdRule) TableName() string {
	return TableNameCrowdRule
}
