// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDataSource = "data_source"

// DataSource mapped from table <data_source>
type DataSource struct {
	SourceID    int64  `gorm:"column:source_id;type:bigint;primaryKey;autoIncrement:true" json:"source_id"` // 数据源ID
	SourceType  int64  `gorm:"column:source_type;type:int;not null" json:"source_type"`                     // 数据源类型
	SourceValue *int64 `gorm:"column:source_value;type:int" json:"source_value"`                            // 类型的具体值
	AppID       int64  `gorm:"column:app_id;type:bigint;not null" json:"app_id"`                            // 应用ID
}

// TableName DataSource's table name
func (*DataSource) TableName() string {
	return TableNameDataSource
}
