// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDataModel = "data_model"

// DataModel mapped from table <data_model>
type DataModel struct {
	ModelID      int64   `gorm:"column:model_id;type:bigint;primaryKey;autoIncrement:true" json:"model_id"` // 数据源ID
	ModelType    int64   `gorm:"column:model_type;type:int;not null" json:"model_type"`                     // 数据源类型
	SourceID     *int64  `gorm:"column:source_id;type:bigint" json:"source_id"`                             // 统计数据源ID
	MlParam      *string `gorm:"column:ml_param;type:text" json:"ml_param"`                                 // 机器学习服务参数
	ModelFeature int64   `gorm:"column:model_feature;type:int;not null" json:"model_feature"`               // 模型用途
}

// TableName DataModel's table name
func (*DataModel) TableName() string {
	return TableNameDataModel
}
