// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRuleElement = "rule_element"

// RuleElement mapped from table <rule_element>
type RuleElement struct {
	RuleElementID    int64  `gorm:"column:rule_element_id;type:bigint;primaryKey;autoIncrement:true" json:"rule_element_id"` // 规则元素ID
	RuleElementValue string `gorm:"column:rule_element_value;type:text;not null" json:"rule_element_value"`                  // 规则元素值
	RuleID           int64  `gorm:"column:rule_id;type:bigint;not null" json:"rule_id"`                                      // 规则ID
}

// TableName RuleElement's table name
func (*RuleElement) TableName() string {
	return TableNameRuleElement
}
