// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRule = "rule"

// Rule mapped from table <rule>
type Rule struct {
	RuleID   int64  `gorm:"column:rule_id;type:bigint;primaryKey;autoIncrement:true" json:"rule_id"` // 规则ID
	RuleType int64  `gorm:"column:rule_type;type:int;not null" json:"rule_type"`                     // 规则类型
	RuleDesc string `gorm:"column:rule_desc;type:text;not null" json:"rule_desc"`                    // 规则描述
	AppID    int64  `gorm:"column:app_id;type:bigint;not null" json:"app_id"`                        // 应用ID
}

// TableName Rule's table name
func (*Rule) TableName() string {
	return TableNameRule
}
