// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSeqMiningTask = "seq_mining_task"

// SeqMiningTask mapped from table <seq_mining_task>
type SeqMiningTask struct {
	TaskID       int64     `gorm:"column:task_id;type:bigint;primaryKey;autoIncrement:true" json:"task_id"` // 挖掘任务ID
	TaskName     string    `gorm:"column:task_name;type:varchar(256);not null" json:"task_name"`            // 任务名
	CreateTime   time.Time `gorm:"column:create_time;type:timestamp;not null" json:"create_time"`           // 任务创建时间
	Status       int64     `gorm:"column:status;type:int;not null" json:"status"`                           // 挖掘状态
	Percent      int64     `gorm:"column:percent;type:int;not null" json:"percent"`                         // 最小支持度
	Event2number *string   `gorm:"column:event2number;type:longtext" json:"event2number"`                   // 事件数据映射编号
	Result       *string   `gorm:"column:result;type:longtext" json:"result"`                               // 挖掘结果
	AppID        int64     `gorm:"column:app_id;type:bigint;not null" json:"app_id"`                        // 应用ID
}

// TableName SeqMiningTask's table name
func (*SeqMiningTask) TableName() string {
	return TableNameSeqMiningTask
}
