// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	UserID   int64  `gorm:"column:user_id;type:bigint;primaryKey;autoIncrement:true" json:"user_id"` // 用户ID
	UserName string `gorm:"column:user_name;type:varchar(256);not null" json:"user_name"`            // 用户名
	AppID    int64  `gorm:"column:app_id;type:bigint;not null" json:"app_id"`                        // 应用ID
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
