// Code generated by hertz generator.

package main

import (
	"backend/dal"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default()

	register(h)

	dal.Init()
	h.Spin()
}
