// Code generated by hertz generator.

package main

import (
	"backend/biz/mw"
	"backend/cmd/dal"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	dal.Init()
	mw.InitJwt()

	h := server.Default()
	
	register(h)
	h.Spin()
}
