// Code generated by hertz generator.

package main

import (
	"backend/biz/mq"
	"backend/biz/mw"
	"backend/cmd/dal"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/config"
)

func main() {
	dal.Init()
	mw.InitJwt()
	mq.Init()

	h := server.Default(config.Option{
		F: func(o *config.Options) {
			o.MaxRequestBodySize = 50 * 1024 * 1024
		},
	})

	register(h)
	h.Spin()
}
